### ISSUE TITLE
glibc error

### ISSUE THREAD

**Issue by coot** [NixOS/docker#11]
I am experiencing this error on circleci:
```
#!/bin/sh -eo pipefail
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
nix-channel --update

Fatal error: glibc detected an invalid stdio handle
Aborted (core dumped)
Exited with code 134
```

**Comment by peti** [comment]
I am sorry, but you'll have to provide way more context for me to be able to understand what is going on.

**Comment by max-arrival** [comment]
This may be related to https://github.com/NixOS/nix/issues/2733

**Comment by peti** [comment]
Good call, @max-arrival. Thank you very much for the link. I think that issue is the correct place to track that problem as it doesn't appear to be specific to the Nix docker image. https://github.com/NixOS/nix/issues/2733#issuecomment-518324335 suggests that this is an issue with `libcurl`.
