### ISSUE TITLE
Could you provide a glibc variant?

### ISSUE THREAD

**Issue by augustocdias** [NixOS/docker#12]
I understand Alpine is a great base image due to its size, but could you provide a glibc variant? 
There are a lot of native applications that rely on glibc and don't work on musl that could benefit from it. I can say for example the rust compiler, that has as lot of limitations when running on alpine.

**Comment by peti** [comment]
I am not sure what you mean. Packages that you install in this docker image are presumably installed with *Nix*, no? These packages should not use Alpine's `glibc`. They should use the `glibc` that comes with Nix. If some Nix-built package uses Alpine's `glibc`, then that's a bug. Are you sure that this issue actually exists with `rust`? Did you try it?

**Comment by augustocdias** [comment]
I think I understood nix completely wrong... I was thinking about evaluating it but when I saw it was in alpine I haven’t even tried.
Sorry...
