### ISSUE TITLE
Image nixos/nix:2.3.4 removed postgres user

### ISSUE THREAD

**Issue by datafoo** [NixOS/docker#17]
The recent [nixos/nix:2.3.4](https://hub.docker.com/layers/nixos/nix/2.3.4/images/sha256-40b406888a8237be46e5a6668599fefdd3c7aad8bbda1d91ae9d71d4d20cf2f6?context=explore) removed the `postgres` user that was present on [nixos/nix:2.3](https://hub.docker.com/layers/nixos/nix/2.3/images/sha256-af330838e838cedea2355e7ca267280fc9dd68615888f4e20972ec51beb101d8?context=explore).

Is that intentional?

I am not too familiar with Docker but from what I understand, the nixos/nix:2.3 dockerfile does not contain any reference to `postgres`. So I imagine that it has to do with the base image [alpine](https://hub.docker.com/_/alpine). Is that right?

**Comment by prusnak** [comment]
Yeah, this seems to originate from the alpine base image.

It also seems right. If there is no postgres installed, why should there be an user for it?
