### ISSUE TITLE
nixpkgs-unstable included in the image

### ISSUE THREAD

**Issue by prusnak** [NixOS/docker#18]
```
$ docker run -i -t nixos/nix /bin/sh -c "du -sh /nix/store/*nixpkgs*"
4.0K	/nix/store/735n9x9w78d97l8y77f71xch3g05iaak-nixpkgs-20.09pre224255.e23f5308583.drv
282.2M	/nix/store/d0zmpyvyhjrq3h2zigjlvcq73x361jdi-nixpkgs-20.09pre224255.e23f5308583
```

I personally use the image to create the latest stable (20.03) environment, so I find it surprising that the base image already contains nixpkgs-unstable. 

This makes the image around 4 times bigger than necessary (the image is around ~90 MB without the channel, adding the channel increases it to ~390 MB).

Is this the original intention?

**Comment by prusnak** [comment]
I just checked and this derivation is not a part of the `nix-2.3.4-x86_64-linux.tar.xz`

**Comment by prusnak** [comment]
Found the culprit in https://github.com/NixOS/nix/blob/672985531c6b9481f8eb8210a17328dfc2515c9b/scripts/install-nix-from-closure.sh#L134 (packaged as `install` in `nix-2.3.4-x86_64-linux.tar.xz`).

So this is a nix packaging bug (or feature)?

**Comment by prusnak** [comment]
An easy fix would be the following change, but I'll open the issue in the nix repo.

```patch
diff --git a/Dockerfile b/Dockerfile
index 2734365..a868289 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -18,6 +18,7 @@ RUN wget https://nixos.org/releases/nix/nix-${NIX_VERSION}/nix-${NIX_VERSION}-x8
   && ln -s /nix/var/nix/profiles/default/etc/profile.d/nix.sh /etc/profile.d/ \
   && rm -r /nix-${NIX_VERSION}-x86_64-linux* \
   && rm -rf /var/cache/apk/* \
+  && /nix/var/nix/profiles/default/bin/nix-channel --remove nixpkgs \
   && /nix/var/nix/profiles/default/bin/nix-collect-garbage --delete-old \
   && /nix/var/nix/profiles/default/bin/nix-store --optimise \
   && /nix/var/nix/profiles/default/bin/nix-store --verify --check-contents
```

**Comment by domenkozar** [comment]
I think a better fix is to be able to get installer to omit creating the channel, since that takes non-trivial amount of time.

**Comment by prusnak** [comment]
> I think a better fix is to be able to get installer to omit creating the channel, since that takes non-trivial amount of time.

Yes. That's why I created a bug in the `nix` repo too: https://github.com/NixOS/nix/issues/3575 so I'll get to learn what is preferred by the `nix` maintainers.

**Comment by prusnak** [comment]
Since https://github.com/NixOS/nix/pull/3588 has been merged we can use the following once `nix-2.3.5` is released.

```
nix-${NIX_VERSION}-x86_64-linux/install --no-channel-add
``

**Comment by prusnak** [comment]
Fixed by https://github.com/NixOS/docker/pull/19

**Comment by prusnak** [comment]
Closing this as the maintainer does not want this change: https://github.com/NixOS/docker/pull/19#discussion_r436338579

**Comment by domenkozar** [comment]
I think we can still provide nix-minimal image as a separate option.

**Comment by garbas** [comment]
With moving the docker image to be generated with Nix the current situation is:

`nixpkgs` channel is added (pointing to unstable) to the list of channels.
Channel is not included in the Nix image, running `nix-channel --update` is required.

The problem of image size is not such a big problem since we are using multi layered image.

Since I'm retiring this repository I'd welcome to open the discussion in `nixos/nix` repository.
