### ISSUE TITLE
cannot execute nix-shell with pinned nixpkgs in CI environment

### ISSUE THREAD

**Issue by allgreed** [NixOS/docker#24]
I'm using this image for executing Docker-based CI flows [in my particular case using Drone Cloud, but I think this applies to all Docker-based CIs]. I have my [nixpkgs pinned](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) for the project in the following way:
```
let
  nixpkgs = builtins.fetchGit {
    name = "...";
    url = "https://github.com/nixos/nixpkgs-channels/";
    ref = "refs/heads/nixos-unstable";
    rev = "...";
  };
```

However when I try to execute any command via `nix-shell --run ...` it fails due to missing git. I've [clumsily added git on top of this image](https://github.com/allgreed/nix-docker) as a hotfix. Not happy about this solution and I'd much rather just use the official images and not maintain my "fork".

Would it be sensible to accommodate this use case in the official images? From what I see you're big on the image size [pun intended], but I think that making nix interoperable with existing tooling is important for adoption. I'd happily provide a PR.

I haven't tried the `fetchTarball` method, it's less preferable as it requires getting the hash on every version change, will have a swing at it if extending the image is a no-go.

**Comment by griff** [comment]
I personally use [niv](https://github.com/nmattia/niv) instead to pin nixpkgs. It usually uses builtins.fetchTarball to fetch nixpkgs behind the scenes but is much nicer to work with and to keep nixpkgs updated. It is also self hosting so that you use niv to keep niv outdated/pinned.

**Comment by peti** [comment]
Why don't you add `git` to `$PATH` as part of your `shell.nix` file? It could be a `nativeBuildInput`, I suppose.

**Comment by garbas** [comment]
It should be easier to extend the docker image now that is being built by Nix.
