### ISSUE TITLE
Arm64 images on Docker Hub

### ISSUE THREAD

**Issue by bobrik** [NixOS/docker#28]
It looks like only amd64 flavor of images is available on Docker hub. It would be nice to have an arm64 equivalent as well.

**Comment by prusnak** [comment]
It should be possible to build images for both amd64 and arm64 via 

```
docker buildx build --platform linux/amd64,linux/arm64 .
```

Other option is to run docker build on two different systems (amd64 and arm64).

**Comment by bobrik** [comment]
IIRC, Github Actions have arm64 agents and you don't have to wait for them for as long as for Travis CI.

**Comment by goodhoko** [comment]
A bit tangential to this issue, but might be handy for folks looking for nix docker image that can run on arm64/aarch64: 

There's an unofficial [nix arm64 image](https://hub.docker.com/r/nickcao/nix-aarch64) at docker hub. [Its layers](https://hub.docker.com/layers/nickcao/nix-aarch64/latest/images/sha256-281fa1d5abccec7aaa97edb142c4341ac755a7f06343203cfc5893659e8b4490?context=explore) seem to be identical to that of the [official image](https://hub.docker.com/layers/nixos/nix/latest/images/sha256-a6bcef50c7ca82ca66965935a848c8c388beb78c9a5de3e3b3d4ea298c95c708?context=explore) and for me it worked as a drop-in replacement but YMMV.

**Comment by NickCao** [comment]
I found it easier to just use nixery.dev/arm64/shell/nixunstable

**Comment by Silex** [comment]
FYI I host a multiarch version of `nixos/nix` at https://hub.docker.com/r/silex/nix

**Comment by garbas** [comment]
This was now done with 2.5.0
