### ISSUE TITLE
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755

### ISSUE THREAD

**Issue by MDobak** [NixOS/docker#34]
I'm trying to build an application that uses the `nix-env` during the `buildPhase`. The build process is being executed from the user `nixbld1` who does not have permission to write to the directory `/nix/var/nix/profiles/`, thus every call to  the`nix-env` during the `buildPhase` returns the following error:

`error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted`

**Comment by peti** [comment]
This is difficult to solve. I believe proper support for build users requires a running `nix-daemon`, which in turn kinda requires an init system, which we don't have. You could adapt your particular build setup to start `nix-daemon`, I guess, but I don't believe that we could easily do that in the generic docker image.
