### ISSUE TITLE
Possibly non-optimal default order of lookups in nsswitch.conf

### ISSUE THREAD

**Issue by kenranunderscore** [NixOS/docker#35]
The line https://github.com/NixOS/docker/blob/e88fd1a6df223b831481683a0ac773656ddb90fc/Dockerfile#L7 makes it so that DNS is asked before checking, for instance, the `/etc/hosts` file. That this file is missing in the first place seems to be a shortcoming of the `alpine` base image itself.

The `ubuntu` image contains this file, but with the `hosts: files dns` line instead of the other way round, which is what I'd expect as default as well. In our case the different order led to some names being resolved to "wrong" IP addresses.

See also https://gitlab.com/gitlab-org/gitlab/-/issues/215471, where the external lookup via DNS with higher priority led to `localhost` being resolved to something other than `127.0.0.1`.

I'd simply open a PR for this but would like to get some feedback first as I'm not 100% sure of the consequences to existing pipelines.

**Comment by peti** [comment]
> I'd simply open a PR for this but would like to get some feedback first as I'm not 100% sure of the consequences to existing pipelines.

I think you are absolutely right and it makes perfect sense to reverse the order of those entries. I don't think that the chances of this change breaking lots of existing installations are very high, so I'd say just go for it. I'd merge a PR for sure.
