### ISSUE TITLE
Docker HUB is dysfunctional for free accounts

### ISSUE THREAD

**Issue by davidak** [NixOS/docker#44]
the latest nix version is 2.3.15. it was also updated in https://github.com/NixOS/docker/commit/df2cbd1482a0c4a457d6f67129b6f440aa20b807 but is not available at https://hub.docker.com/r/nixos/nix/tags?page=1&ordering=last_updated

**Comment by peti** [comment]
Yes, Docker HUB is no longer offering continuous builds for free. We'd need a paid account to continue using the service. It might also be possible to figure out a way to build those images here on Github, e.g. via github actions and to publish the build results on Docker HUB. I'm not sure though, I haven't followed this whole situation closely.

**Comment by garbas** [comment]
This is now irrelevant. Docker image is now built with hydra.
