### ISSUE TITLE
Where is configuration.nix ?

### ISSUE THREAD

**Issue by caike** [NixOS/docker#48]
Newb to NixOS here - is there supposed to be a default `configuration.nix` file somewhere ? If so, I can't find it.

I'm trying to run `nix-shell` for a project that's setup for nix, and need to add configurations for `binaryCaches` and `binaryCachePublicKeys`, like so:

```
nix = {
  binaryCaches          = [ "..." "..." ];
  binaryCachePublicKeys = [ "..." "...." ];
};
```

Any pointes to where I should add this ? Using this Docker image, I can't seem to find the recommended `configuration.nix` file. Should I add it to the project's `shell.nix` file ? Appreciate any and all help 🙏

**Comment by peti** [comment]
This container is not running NixOS. It's an minimal Alpine Linux with the Nix package manager installed. There is no configuration.nix in this container.
