### ISSUE TITLE
Update nix to 2.4

### ISSUE THREAD

**Issue by Omrigan** [NixOS/docker#51]

**Comment by erikarvstedt** [comment]
[nixos/nix:latest](https://hub.docker.com/layers/nixos/nix/latest/images/sha256-acb00d7a40177611cb5c8b4fd62eeaf3406b13dfd38e875b74d13d2f7eeda07e?context=explore) now uses Nix 2.5.0.

**Comment by garbas** [comment]
I'm also working on backporting the changes in nix to also push docker image 2.4.0
