### ISSUE TITLE
Sources of the 2.5.0 image

### ISSUE THREAD

**Issue by LeSuisse** [NixOS/docker#53]
Hello,

An image with a 2.5.0 tag has been published to Docker Hub 8 hours ago but the sources does not seem to be present in this repository.

Is the image generated from another repository?

cc @garbas since it looks like the new images has been pushed with your account on the Docker Hub.

**Comment by garbas** [comment]
@LeSuisse Thank you for the ping.

The 2 images were build by hydra ([amd64](https://hydra.nixos.org/build/161439803), [arm64](https://hydra.nixos.org/build/161439781)). I then created a manifest to "join" them. The source for building nix docker image is now in `nixos/nix` repository.

I'll be working this week on automating preview releases for master branch. I'll also archive this repository.

**Comment by LeSuisse** [comment]
Thanks for the clarification :+1:
