### ISSUE TITLE
Channel update fails with latest nixos/nix image

### ISSUE THREAD

**Issue by lriesebos** [NixOS/docker#56]
With the latest update to Nix 2.5, Nix channel updates fail.
See the following case:

```
leon@artiq-mblab:~$ docker run -i -t nixos/nix:latest
bash-4.4# nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
bash-4.4# nix-channel --update
unexpected error in download thread: error: unsharing filesystem state in download thread: Operation not permitted
error: download of 'https://nixos.org/channels/nixpkgs-unstable' was interrupted
```

This problem does not occur when using the older Nix 2.3.x image using `docker run -i -t nixos/nix:2.3.12`

Am I overseeing something with the change to Nix 2.5, or is this an actual bug? @garbas

**Comment by garbas** [comment]
As far as I can tell this is a bug in Nix 2.5
. I already pinged the responsible developer that introduced the change.

**Comment by garbas** [comment]
I'll close the issue here since I'm already tracking it in the nix repository. I hope to have fix out soon.
