### ISSUE TITLE
Missing Dockerfile for nixos/nix:2.5.0

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/docker#57]
I noticed that nixos/nix:2.5.0 was added a day ago (15th December) and it seems there are some breaking changes (i.e /bin/sh is missing). Reading the `Dockerfile` in this repository, it appears that it doesn't correspond to the one built and uploaded to Docker Hub.

**Comment by vdovhanych** [comment]
This seems to be related to https://github.com/NixOS/nix/pull/5453 and further work on this. It should be mentioned here in the readme probably. I guess @garbas will have more insight into this.

**Comment by garbas** [comment]
There is no Dockerfile since the docker image is built with nix.
