### ISSUE TITLE
arm/v7 images

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/docker#9]
Hi,

I would like to use [nix-emacs-ci](https://github.com/purcell/nix-emacs-ci) but my CI environment only has arm/v7 slaves. Would you mind adding support for arm/v7 builds?

**Comment by peti** [comment]
How do we do that? Can hub.docker.com provide those images?

**Comment by DamienCassou** [comment]
I'm not really sure, but I think this might help:

- https://docs.docker.com/registry/spec/manifest-v2-2/
- https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6

**Comment by peti** [comment]
I am sorry, but I don't understand any of that material. I don't see how it applies to our docker builds at hub.docker.com.

**Comment by DamienCassou** [comment]
I think adding a manifest file in the repo with the list of architectures might be enough for hub.docker.com to start building for multiple architectures. But I'm no expert though.

**Comment by peti** [comment]
Well, if you can figure out how to do this and give me some reasonably easy to follow instructions (or a pull-request here), then I'll happily enable the additional platform. I don't have the chance to get into researching this topic myself, though. I am sorry I can't be more helpful.

**Comment by DamienCassou** [comment]
I understand @peti. I was secretly hoping you would know more than me :-).

**Comment by DamienCassou** [comment]
From what I understand now, it seems docker hub only builds automatically for x86_64. If we want to support other architectures, we need to build the images locally and push them to docker hub. Moreover, the Dockerfile in your repository needs to be changed to support armv7 because Nix's official repository doesn't have releases for armv7 architecture.

You may close the issue.

**Comment by peti** [comment]
I see, It's a shame it's not easier to support that platform.
